[package]
name = "minimal-auth"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aes = "0.8"
argon2 = "0.5"
base64 = "0.22"
cbc = { version = "0.1", features = ["alloc", "block-padding"] }
md-5 = "0.10"
minimal-otp = { path = "../minimal-otp" }
percent-encoding = "2"
serde = "1"
serde_json = "1"
thiserror = "2"
url = "2"
zeroize = "1"

[lints]
workspace = true
